### ISSUE TITLE
Regarding XILINXD_LICENSE_FILE environment variable

### ISSUE THREAD

**Issue by harshgondaliya** [NetFPGA/P4-NetFPGA-public#26]
My Xilinx Vivado license is a node blocked license and the 10G MAC & SD-Net are floating licenses. Therefore, I have two license files.
Should I copy paste content of one license file to another and make a single license file, and then set value of `XILINXD_LICENSE_FILE` to it's path?

**Comment by sibanez12** [comment]
You shouldn't need to combine licenses into one file as long as they are both in your path. To check if they are both in your path run `$ vlm` and look for all your expected licenses. If you find them then you're good to go.

**Comment by harshgondaliya** [comment]
Yes I am able to see all my licenses in the `vlm`. Thanks.
