### ISSUE TITLE
Cannot see the network port information after NetFPGA SUME driver is loaded

### ISSUE THREAD

**Issue by zhangzicheng0428** [NetFPGA/P4-NetFPGA-public#52]
Hello!

I now use the NetFPGA SUME development board for some tests. The experiment is completed according to the steps in the test document (such as screenshots). After loading the driver during the test, the network interface information cannot be viewed in the system (Go to step 7). The details are as follows:
![image](https://user-images.githubusercontent.com/35160702/96208055-43676b80-0f9f-11eb-93c7-49275c128844.png)

1.system message：

CPU:Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

Motherboard model：Gigabyte B150M-VP

Operating system: Ubuntu 16.4

Kernel version: 4.15.0-120-generic

2.Test operation steps：

a.On the xsct console, use connect and then fpga -f reference_nic.bit to program the FPGA with the bitfile and exit to close xsct console. Reboot the machine.

![image](https://user-images.githubusercontent.com/35160702/96208372-ea4c0780-0f9f-11eb-83cd-d0f5bb411d28.png)

b.Check that the bitfile file is successfully burned

![image](https://user-images.githubusercontent.com/35160702/96208195-8cb7bb00-0f9f-11eb-898f-0e502f205663.png)

c.Build the driver for the NetFPGA SUME board.

![image](https://user-images.githubusercontent.com/35160702/96208231-a6590280-0f9f-11eb-9f27-6f967c86398d.png)

d.View network interface information in the system

![image](https://user-images.githubusercontent.com/35160702/96208267-b8d33c00-0f9f-11eb-99d6-df512e77cf43.png)

In the fourth step "c", you can see that there are four more interfaces after loading the driver, but these four interfaces are not the "nfx" interfaces mentioned in step 7, and cannot be viewed by using ethtool Find the interface information, and cannot UP and configure the IP address?

**Comment by ghost** [comment]
Hello, if you could follow instructions in  this wiki page -> [ Network Setup for Ubuntu 2020.4 LTS](https://github.com/NetFPGA/NetFPGA-SUME-public/wiki/Network-Setup-for-Ubuntu-2020.4-LTS) your issue will be resolved

**Comment by zhangzicheng0428** [comment]
> Hello, if you could follow instructions in this wiki page -> [ Network Setup for Ubuntu 2020.4 LTS](https://github.com/NetFPGA/NetFPGA-SUME-public/wiki/Network-Setup-for-Ubuntu-2020.4-LTS) your issue will be resolved

Thanks! Hilx 

The system I am debugging is ubuntu 16.04, the version mentioned on the connection is version 2020.4, and netplan cannot be found in the etc directory on 16.04.

**Comment by salvatorg** [comment]
Hi @zhangzicheng0428 ,

Have you tried [this](https://github.com/NetFPGA/NetFPGA-SUME-public/wiki/Reference-Operating-System-Setup-Guide#network-interface-names-ubuntu-1604)
