### ISSUE TITLE
how to program bitstream file into Flash memory.

### ISSUE THREAD

**Issue by wangmengsail** [NetFPGA/P4-NetFPGA-public#53]
hello,everyone!

I just buy a NetSume FPGA board, but I don't know how to program bitstream file into Flash memory.

First things first, I checked that JP1 is not shorted. Then I run  through this guide: https://github.com/NetFPGA/NetFPGA-SUME-public/wiki/Reference-Operating-System-Setup-Guide. After I complete it, I run the following command at the terminal:

dsumecfg write -d NetSUME -f production_test.bit -s 0 -verify

Error information at the terminal  is following:

Configuring FPGA...
FPGA configuration succeeded.
Erasing Flash: 0%ERROR: timed out after 25000ms while waiting for FPGA handshake
ERROR: FPGA handshake failed while erasing blocks blocks 0 - 5

It is also possible that the CPLD XC2c512 was erased when I run the following command at the terminal:

djtgcfg  erase -i 1 -d NetSUME

How can I resolve the problem if  this is the case?

You can see the error information in the final sreenshot
![viewfile](https://user-images.githubusercontent.com/70922355/96328244-50558f00-1073-11eb-89ed-4bf1b3f56e6b.png)
 
![viewfile(1)](https://user-images.githubusercontent.com/70922355/96328246-55b2d980-1073-11eb-9577-e5ed3d640365.png)
![viewfile(2)](https://user-images.githubusercontent.com/70922355/96328249-5cd9e780-1073-11eb-911b-c738163ad8c0.png)
The flash section 0,1,2,3 are not blank because I checked the flash with command "dsumecfg blankcheck ......."

**Comment by salvatorg** [comment]
Refer to [issue 57](https://github.com/NetFPGA/NetFPGA-SUME-live/issues/57)

Double post
