### ISSUE TITLE
Is code request form still available?

### ISSUE THREAD

**Issue by kyeot95** [NetFPGA/P4-NetFPGA-public#68]
I''m sorry for uploading this question in [issues].
I send code access request form about two weeks ago
and I still got no reply.
I also send emails to contact netfpga and got no reply either.
Is code request form still available?
or am I just been rejected to code access?

**Comment by salvatorg** [comment]
Apologies for the delay, your request will be processed asap.

**Comment by kyeot95** [comment]
Did I took it wrong..?
I understand the access permission is about  [https://github.com/NetFPGA/NetFPGA-SUME-live].
and No. I still don't have permission to above site.

I'll send another request form.
My email is **kyeo95@naver.com** or **kyeot95@gmail.com** 
either email is okay.

**Comment by salvatorg** [comment]
There are two separate repos for NetFPGA-SUME and P4-NetFPGA which have 2 separate registration forms.
In any case the invitation to access NetFPGA-SUME-live has been sent to you.
